-- OBYWATELSTWA
INSERT INTO obywatelstwa(id_obywatelstwa, obywatelstwo) VALUES (1, 'polskie');

COMMIT;

-- UPRAWNIENIA
INSERT INTO uprawnienia(id, name) VALUES (1, 'USER');

COMMIT;

-- SEKWENCJE
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ACCOUNT_SEQ START WITH 1 INCREMENT BY 1;
COMMIT;
