-- UŻYTKOWNICY
CREATE TABLE USERS (
	ID INTEGER NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	SURNAME VARCHAR(100) NOT NULL,
	LOGIN VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(128) NOT NULL,
	PRIMARY KEY (ID)
	-- reszta pól do dopisania
);

CREATE TABLE ROLES (
	ID INTEGER NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLES (
	ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	ROLE_ID INTEGER NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT USER_ROLES_00_USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
	CONSTRAINT USER_ROLES_00_ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);

COMMIT;