--liquibase formatted sql

--changeset qbisiak:5
  CREATE TABLE HISTORIA_KART 
   (	ID NUMBER(10,0), 
	AMMOUNT NUMBER(19,2), 
	TIMESTAMP DATE, 
	CARD_ID NUMBER(10,0), 
	OPERATION_ID NUMBER(10,0)
   );

  CREATE TABLE KARTY 
   (	CARD_TYPE VARCHAR2(31), 
	ID NUMBER(10,0), 
	ACTIVATION_DATE DATE, 
	DIALY_CASH_MAX_AMMOUNT NUMBER(19,2), 
	ENABLED CHAR(1), 
	EXPIRATION_DATE DATE, 
	LIMIT NUMBER(19,2), 
	LOCKED CHAR(1), 
	DIALY_NONCASH_MAX_AMMOUNT NUMBER(19,2), 
	CARD_NUMBER VARCHAR2(16), 
	PIN VARCHAR2(4), 
	DIALY_PROXIMITY_MAX_AMMOUNT NUMBER(19,2), 
	DIALY_PROXIMITY_MAX_OPS NUMBER(19,2), 
	SECURE_CODE VARCHAR2(4), 
	DIALY_LIMIT NUMBER(19,2), 
	INTEREST NUMBER(19,2), 
	REPORTING_DAY NUMBER(10,0), 
	INTEREST_FREE_DAYS NUMBER(10,0), 
	ACCOUNT_ID_RACHUNEK NUMBER(10,0), 
	OWNER_ID_KLIENT NUMBER(10,0), 
	ACCOUNT_TO_CHARGE NUMBER(10,0)
   );

  CREATE TABLE OPERACJE_KARTA 
   (	ID NUMBER(10,0), 
	CARD_DISCRIMINATOR VARCHAR2(255), 
	CARD_OPERATION_TYPE VARCHAR2(255), 
	INTEREST NUMBER(19,2), 
	PRICE NUMBER(19,2)
   );

   CREATE UNIQUE INDEX SYS_C007747 ON HISTORIA_KART (ID);

   CREATE UNIQUE INDEX SYS_C007753 ON KARTY (ID);

   CREATE UNIQUE INDEX SYS_C007781 ON OPERACJE_KARTA (ID);
   

--changeset qbisiak:6
   CREATE SEQUENCE KARTY_SEQ START WITH 10 INCREMENT BY 1;
   CREATE SEQUENCE HISTORIA_KART_SEQ START WITH 10 INCREMENT BY 1;
   CREATE SEQUENCE OPERACJE_KARTA_SEQ START WITH 10 INCREMENT BY 1;