--liquibase formatted sql

--changeset samoSieZrobilo:3
CREATE TABLE CYCLIC_TRANSFERS (
    ID INT NOT NULL PRIMARY KEY,
    USER_ID INT NOT NULL,
    DEBIT_ACCOUNT_ID INT NOT NULL,
    ACCOUNT_NUMBER VARCHAR(26) NOT NULL,
    AMOUNT DECIMAL(20,5) DEFAULT 0 NOT NULL,
    DAY_OF_MONTH NUMBER(2) NOT NULL,
    NAME VARCHAR(512) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    STREET VARCHAR(100) NOT NULL,
    STREET_NO VARCHAR(30) NOT NULL,
    ZIPCODE VARCHAR(6) NOT NULL,
    CONSTRAINT CYC_TRANS_FK_USER FOREIGN KEY (USER_ID) REFERENCES klienci(id_klient),
    CONSTRAINT CYC_TRANS_FK_DEBIT_ACCOUNT FOREIGN KEY (USER_ID) REFERENCES rachunki(id_rachunek)
);

CREATE TABLE DEFINDED_RECIPIENTS (
    ID INT NOT NULL PRIMARY KEY,
    USER_ID INT NOT NULL,
    ACCOUNT_NUMBER VARCHAR(26) NOT NULL,
    NAME VARCHAR(512) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    STREET VARCHAR(100) NOT NULL,
    STREET_NO VARCHAR(30) NOT NULL,
    ZIPCODE VARCHAR(6) NOT NULL,
    CONSTRAINT DEFINDED_RECIPIENTS_FF_USER FOREIGN KEY (USER_ID) REFERENCES klienci(id_klient)
);

CREATE SEQUENCE DEFINDED_RECIPIENTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CYCLIC_TRANSFERS_SEQ START WITH 1 INCREMENT BY 1;
